name: Daily Commit with Timestamp

on:
  schedule:
    - cron: '0 6 * * *'  # Every day at 6 AM UTC
  workflow_dispatch:  # Optional: allow manual trigger

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3

    - name: Update README with timestamp
      run: |
        echo "Updating timestamp..."
        TIMESTAMP=$(date -u)
        sed -i "s|_Last updated: .*_|_Last updated: $TIMESTAMP_|" README.md

    - name: Commit and Push Changes
      env:
        TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m "🤖 Auto update: $(date -u)" || echo "No changes to commit"
        git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git HEAD:main
